### PR TITLE
Helper.log is deprecated. Use `UI` class instead

### PR DESCRIPTION
**Pull request by chraibi**
Using `fastlane 1.110.0` I get the following warning 

```
Helper.log is deprecated. Use `UI` class instead
```

Using `UI` as suggested by the warning message helps instead. 
screen shot 2016-11-25 at 14 58 16

### CODE REVIEW

**Comment by iv-mexx** [comment]
Hey, thanks for the Merge Request, this is great!
But it's conflicting with master, could you base these changes on the most recent version of master?

**Comment by chraibi** [comment]
Does this not work?

**Comment by iv-mexx** [comment]
@chraibi Oh sorry, I beliefe theres no notification when commits are added to a pull request, so I didn't notice that you've changed anything until now!
Will take a look right now!

**Comment by iv-mexx** [comment]
Yeah it works, this is great! Thanks for the help 👍

**Pull request merged**
